Bsa2er MVC/Bsa2er MVC/Models/CarouselImage.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Bsa2er_MVC.Models
{
    public class CarouselImage
    {
        public int Id { get; set; }
        public string ImagePath { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }
    }
}

Bsa2er MVC/Bsa2er MVC/Controllers/CarouselImageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bsa2er_MVC.Models;

namespace Bsa2er_MVC.Controllers
{
    public class CarouselImageController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: CarouselImage
       /* public async Task<ActionResult> Index()
        {
            return View(await db.CarouselImages.ToListAsync());
        }*/

        // GET: CarouselImage/Details/5
       /* public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarouselImage carouselImage = await db.CarouselImages.FindAsync(id);
            if (carouselImage == null)
            {
                return HttpNotFound();
            }
            return View(carouselImage);
        }*/

        // GET: CarouselImage/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CarouselImage/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CarouselImage carouselImage)
        {
            if (ModelState.IsValid)
            {
                carouselImage.ImagePath = "default.jpg";
                if (carouselImage.ImageFile != null)
                {
                    string[] arr = carouselImage.ImageFile.FileName.Split('.');
                    string imageName = Guid.NewGuid().ToString() + "." + arr[arr.Length - 1];
                    carouselImage.ImageFile.SaveAs(Server.MapPath("~/images/CarouselImages/") + imageName);
                    carouselImage.ImagePath = imageName;
                }
                db.CarouselImages.Add(carouselImage);
                await db.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }

            return View(carouselImage);
        }

        // GET: CarouselImage/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarouselImage carouselImage = await db.CarouselImages.FindAsync(id);
            if (carouselImage == null)
            {
                return HttpNotFound();
            }
            return View(carouselImage);
        }

        // POST: CarouselImage/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit( CarouselImage carouselImage)
        {
            if (ModelState.IsValid)
            {
                if (carouselImage.ImageFile != null)
                {
                    string[] arr = carouselImage.ImageFile.FileName.Split('.');
                    string imageName = Guid.NewGuid().ToString() + "." + arr[arr.Length - 1];

                    if (carouselImage.ImagePath != null)
                    {
                        System.IO.File.Delete(Server.MapPath("~/images/CarouselImages/") + carouselImage.ImagePath);
                    }
                    carouselImage.ImageFile.SaveAs(Server.MapPath("~/images/CarouselImages/") + imageName);
                    carouselImage.ImagePath = imageName;
                }
                db.Entry(carouselImage).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index","Home");
            }
            return View(carouselImage);
        }

        // GET: CarouselImage/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarouselImage carouselImage = await db.CarouselImages.FindAsync(id);
            if (carouselImage == null)
            {
                return HttpNotFound();
            }
            return View(carouselImage);
        }

        // POST: CarouselImage/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            CarouselImage carouselImage = await db.CarouselImages.FindAsync(id);
            db.CarouselImages.Remove(carouselImage);
            await db.SaveChangesAsync();
            return RedirectToAction("Index","Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Bsa2er MVC/Bsa2er MVC/Views/CarouselImage/Create.cshtml
@model Bsa2er_MVC.Models.CarouselImage

@{
    ViewBag.Title = "انشاء صورة";
}

    <h2 dir="rtl" class="text-center mb-5">انشاء صورة جديدة</h2>

@using (Html.BeginForm("Create", "CarouselImage", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal text-right mb-2 mt-2" dir="rtl" style="height:50px">
 
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group" style="height:40px;" dir="rtl">
            <label id="imagePath" class="control-label col-md-2">ادخل الصورة</label>
            @*@Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                <input type="file" id="imagePath" name="ImageFile" class = "form-control" />
                @*@Html.EditorFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control" } })*@
                @*@Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="انشأ" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("الرجوع الى الصفحة الرئيسية", "Index","Home",null,null)
</div>

Bsa2er MVC/Bsa2er MVC/Views/CarouselImage/Delete.cshtml
@model Bsa2er_MVC.Models.CarouselImage

@{
    ViewBag.Title = "حذف صورة";
}

<h2 class="text-center mb-3" dir="rtl">حذف الصورة</h2>

<h3 class="text-right mr-3" dir="rtl">هل انت متأكد تريد حذف هذه الصورة؟</h3>
<div class=" justify-content-between text-right mr-3" dir="rtl" style="min-height:200px;">

    <dl class="dl-horizontal">
        <dt>
            <lable id="img">الصورة </lable>
        </dt>

        <dd>
            <img height="150" width="150" id="img" src="~/images/CarouselImages/@Model.ImagePath" />
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="حذف" class="btn btn-primary" />  |
           @Html.ActionLink("الرجوع الى الصفحة الرئيسية", "Index", "Home", null, null)
        </div>
    }
</div>

Bsa2er MVC/Bsa2er MVC/Views/CarouselImage/Details.cshtml
@model Bsa2er_MVC.Models.CarouselImage

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>CarouselImage</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImagePath)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Bsa2er MVC/Bsa2er MVC/Views/CarouselImage/Edit.cshtml
@model Bsa2er_MVC.Models.CarouselImage

@{
    ViewBag.Title = "تعديل صورة";
}

    <h2 class="text-center text-right" dir="rtl">تعديل الصورة</h2>

@using (Html.BeginForm("Edit", "Gallery", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal text-right" dir="rtl" style="height:250px;">

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group" style="height:100px">
        <label class="control-label col-md-2"> الصورة</label>
        @*@Html.LabelFor(model => model.Gallery_path, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="col-md-10">
            <img width="150" height="150" src="~/images/CarouselImages/@Model.ImagePath" />
            @*@Html.EditorFor(model => model.Gallery_path, new { htmlAttributes = new { @class = "form-control" } })*@
            @*@Html.ValidationMessageFor(model => model.Gallery_path, "", new { @class = "text-danger" })*@
        </div>
    </div>

    <div class="form-group" dir="rtl" style="height:70px">
        <label class="control-label col-md-2">ادخل الصورة الجديدة</label>
        @*@Html.LabelFor(model => model.Gallery_path, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="col-md-10">
            <input type="file" class="form-control" accept="image" name="ImageFile" />
            @*@Html.EditorFor(model => model.Gallery_path, new { htmlAttributes = new { @class = "form-control" } })*@
            @*@Html.ValidationMessageFor(model => model.Gallery_path, "", new { @class = "text-danger" })*@
        </div>
    </div>

    <div class="form-group" dir="rtl">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="حفظ" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("الرجوع الى الصفحة الرئيسية", "Index", "Home", null, null)
</div>

Bsa2er MVC/Bsa2er MVC/Views/CarouselImage/Index.cshtml
@model IEnumerable<Bsa2er_MVC.Models.CarouselImage>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ImagePath)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ImagePath)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>