Bsa2er MVC/Bsa2er MVC/Models/Booksection.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web;

namespace Bsa2er_MVC.Models
{
    public class Booksection
    {

        public Booksection()
        {
            this.Books = new HashSet<Book>();
        }
        [Key]
        public int id { set; get; }

        public String title { set; get; }

        [NotMapped]
        public HttpPostedFileBase Image { set; get; }
        public string imagepath { set; get; }

        public ICollection<Book> Books { set; get; }

    }
}

Bsa2er MVC/Bsa2er MVC/Models/Gallery.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Bsa2er_MVC.Models
{
    public class Gallery
    {
        [Key]
        public int G_Id { get; set; }
        public string Gallery_path { get; set; }
    }
}

Bsa2er MVC/Bsa2er MVC/Models/news.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web;

namespace Bsa2er_MVC.Models
{
    public class news
    {
        [Key]
        public int id { set; get; }

        [Display(Name ="عنوان الخبر")]
        public string title { set; get; }
        [Display(Name ="محتوى الخبر")]
        public string body { set; get; }

        [NotMapped]
        public HttpPostedFile Image { set; get; }

        public string ImagePath { set; get; }

    }
}

Bsa2er MVC/Bsa2er MVC/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bsa2er_MVC.Models;

namespace Bsa2er_MVC.Controllers
{
    [Authorize]
    public class BooksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Books
        public ActionResult Index(int ? id)
        {
            if (id == null)
                return View(db.Books.ToList());
            else
            {
                return View(db.Booksections.Include(a => a.Books).FirstOrDefault(a => a.id == id).Books);
                        }
        }

        // GET: Books/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // GET: Books/Create
        public ActionResult Create(int id)
        {
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int id, Book book)
        {
         if(System.IO.Path.HasExtension(book.PdfFile.FileName)== false)
            {
                ModelState.AddModelError("", "قم بادخال الملف بصيغة بي دي اف ");
            }
            if (ModelState.IsValid)
            {
                String[] array = book.ImageFile.FileName.Split('.');
                String filename = Guid.NewGuid() + "." + array[array.Length - 1];
                String[] array1 = book.PdfFile.FileName.Split('.');
                String filename1 = Guid.NewGuid() + "." + array1[array1.Length - 1];

                if (array[array.Length - 1].ToLower() != "jpg"  &&  array[array.Length - 1].ToLower() !="jpeg" )

                {
                    ModelState.AddModelError("", "من فضلك قم بادخال الصورة  بصيغة جي بي جي او جي بي اي جي ");

                    return View();
                }
                else if (array1[array1.Length-1].ToLower()!="pdf" )
                {
                    ModelState.AddModelError("","قم بادخال الملف بصيغة بي دي اف ");
                    return View();

                }

                book.ImageFile.SaveAs(Server.MapPath("~/images/Books/") + filename);
                book.imageFilePath = filename;
             
                book.PdfFile.SaveAs(Server.MapPath("~/texts/") + filename1);
                book.PdfFilepath = filename1;
              Booksection b =db.Booksections.Include(a=>a.Books).FirstOrDefault(a => a.id == id);
                b.Books.Add(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(book);
        }

        // GET: Books/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( Book book)
        {
            if (ModelState.IsValid)
            {
                String[] array = book.ImageFile.FileName.Split('.');
                String filename = Guid.NewGuid() + "." + array[array.Length - 1];
                book.ImageFile.SaveAs(Server.MapPath("~/images/Books/") + filename);
                book.imageFilePath = filename;
                String[] array1 = book.PdfFile.FileName.Split('.');
                String filename1 = Guid.NewGuid() + "." + array1[array1.Length - 1];
                book.PdfFile.SaveAs(Server.MapPath("~/texts/") + filename1);
                book.PdfFilepath = filename1;
                db.Entry(book).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(book);
        }

        // GET: Books/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book book = db.Books.Find(id);
            db.Books.Remove(book);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Bsa2er MVC/Bsa2er MVC/Controllers/BooksectionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bsa2er_MVC.Models;

namespace Bsa2er_MVC.Controllers
{
    [Authorize]
    public class BooksectionsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            return View(db.Booksections.ToList());
        }

        // GET: Booksections/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booksection booksection = db.Booksections.Find(id);
            if (booksection == null)
            {
                return HttpNotFound();
            }
            return View(booksection);
        }

        // GET: Booksections/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Booksections/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Booksection booksection)
        {
            if (ModelState.IsValid)
            {
                if (booksection.Image != null)
                {
          
                    String[] array = booksection.Image.FileName.Split('.');
                    if (array[array.Length - 1].ToLower() !="jpg" && array[array.Length - 1].ToLower() != "jpeg")
                    {
                        ModelState.AddModelError("imageproblem", "من فضلك قم بادخال صورة بامتداد jpg"  );
                        return View();
                    }


                    String filename = Guid.NewGuid() + "." + array[array.Length - 1];
                    booksection.Image.SaveAs(Server.MapPath("~/images/Booksections/")+filename);
                    booksection.imagepath = filename;
                }
                db.Booksections.Add(booksection);
                db.SaveChanges();
                return RedirectToAction("DashBoardPage","DashBoard");
            }

            return View(booksection);
        }

        // GET: Booksections/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booksection booksection = db.Booksections.Find(id);
            if (booksection == null)
            {
                return HttpNotFound();
            }
            return View(booksection);
        }

        // POST: Booksections/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Booksection booksection)
        {
            if (ModelState.IsValid)
            {
                String[] array = booksection.Image.FileName.Split('.');
                String filename = Guid.NewGuid() + "." + array[array.Length - 1];
                booksection.Image.SaveAs(Server.MapPath("~/images/Booksections/") + filename);
                booksection.imagepath = filename;
                db.Entry(booksection).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("DashBoardPage", "DashBoard");
            }
            return View(booksection);
        }

        // GET: Booksections/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booksection booksection = db.Booksections.Find(id);
            if (booksection == null)
            {
                return HttpNotFound();
            }
            return View(booksection);
        }

        // POST: Booksections/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Booksection booksection = db.Booksections.Include(a=>a.Books).FirstOrDefault(a=>a.id==id);
            db.Booksections.Remove(booksection);
            db.SaveChanges();
            return RedirectToAction("DashBoardPage", "DashBoard");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Bsa2er MVC/Bsa2er MVC/Controllers/NewsController.cs
using Bsa2er_MVC.Models;
using Bsa2er_MVC.Repositories;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Bsa2er_MVC.Controllers
{
    
    public class NewsController : Controller
    {
        //private ApplicationDbContext db = new ApplicationDbContext();

        private IRepository<news> _newsRepository;
        public NewsController(IRepository<news> newsRepository)
        {
            _newsRepository = newsRepository;
        }

        // GET: news
       /* public ActionResult Index()
        {
            return View(db.News.ToList());
        }*/

        // GET: news/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            news news = _newsRepository.FindById(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // GET: news/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: news/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "title,body")] news news, HttpPostedFileBase imageFile)
        {
            if (ModelState.IsValid)
            {
                if (imageFile != null)
                {
                    string[] arr = imageFile.FileName.Split('.');
                    string filename = Guid.NewGuid().ToString() + "." + arr[arr.Length - 1];
                    imageFile.SaveAs(Server.MapPath("~/images/News/") + filename);
                    news.ImagePath = filename;
                }

                _newsRepository.AddItem(news);
                return RedirectToAction("Index","Home");
            }

            return View(news);
        }

        // GET: news/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            news news = _newsRepository.FindById(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // POST: news/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,title,body,ImagePath")] news news, HttpPostedFileBase imgFile)
        {
            if (ModelState.IsValid)
            {
                if (imgFile != null)
                {
                    string[] arr = imgFile.FileName.Split('.');
                    string imageName = Guid.NewGuid().ToString() + "." + arr[arr.Length - 1];

                    if (news.ImagePath != null)
                    {
                        System.IO.File.Delete(Server.MapPath("~/images/News/") + news.ImagePath);
                    }
                    imgFile.SaveAs(Server.MapPath("~/images/News/") + imageName);
                    news.ImagePath = imageName;
                }
                _newsRepository.EditItem(news);
                return RedirectToAction("Index");
            }
            return View(news);
        }

        // GET: news/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            news news = _newsRepository.FindById(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // POST: news/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            news news = _newsRepository.FindById(id);
            _newsRepository.Remove(news);
            return RedirectToAction("Index");
        }

        public ActionResult NewsDetails(int id)
        {
            news news = _newsRepository.FindById(id);
            return PartialView(news);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _newsRepository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Bsa2er MVC/Bsa2er MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "عن الاكاديمية";
}
<div class="row container-fluid">
    <iframe class=" col-lg-4" width="60%" height="250" style="margin-top: 5%;margin-left: 8%;" src="https://www.youtube.com/embed/GBV3wshEpvM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <div class="col-lg-7 my-5 pr-5" style="text-align:right;direction: rtl;">
        <h3>عن الاكاديمية</h3>
        <p>أكاديمية قائمة على بث العلم الشرعي النافع للمسلم والمسلمة</p>
        <h3>رؤية ورسالة الأكاديمية</h3>
        <p>الريادة في تعليم العلوم الشرعية وفق برامج ومناهج تأصيلية</p>
        <h3>أهداف الأكاديمية</h3>
            <p>تقريب العباد من ربهم</p>
            <p>رفع الجهل عن عامة المسلمين في أحكام الشريعة العينية</p>
            <p>بيان وتوضيح منهج خير القرون والسير على هداهم</p>
            <p>توفير برامج ودورات علمية مؤصلة لجميع مستويات طلاب وطالبات العلم</p>
    </div>
</div>

Bsa2er MVC/Bsa2er MVC/Views/Home/BookSection.cshtml
@model IEnumerable<Bsa2er_MVC.Models.Booksection>

@{
    ViewBag.Title = "قسم الكتب";
}

    <div class=" container">
        <h1 class="h1 text-center m-4">أقسام الكتب</h1>
        <div class="row " dir="rtl">
      
            @foreach (var item in Model)
            {
                <div class="card col-md-4 ml-2 mt-3">
                    <div class="card-header text-center">
                        @Html.DisplayFor(modelItem => item.title)

                    </div>
                    <div class="card-body text-center">

                        <img class="card-img" src="~/images/Booksections/@item.imagepath" width="100%" height="100%" />


                    </div>
                    <div class="card-footer text-center">

                        @Html.ActionLink("الكتب", "Index", "Books", new { id = item.id }, new { @class = "btn btn-dark mt-md-2" })

                    </div>


                </div>




            }
           
        </div>
    </div>

Bsa2er MVC/Bsa2er MVC/Views/Home/Contact.cshtml
@model Bsa2er_MVC.Controllers.message

@{ 
    ViewBag.Title = "اتصل بنا";
}
<div class="container ">
    <div class="row my-5">
        <div class="col-12 col-lg-6" style="text-align:center;">
            <img src="~/images/4.png" width="80%" alt="img" /></br>
            <a class="fa fa-facebook text-primary  btn btn-toolbar  fa-2x p-4 mb-3" target="_blank"
               href="https://www.facebook.com/"></a>
            <a class="fa fa-twitter text-info   btn btn-toolbar  fa-2x p-4 mb-3" target="_blank"
               href="https://twitter.com/"></a>
            <a class="fa fa-instagram text-warning   btn btn-toolbar  fa-2x p-4 mb-3" target="_blank"
               href="https://github.com/"></a>
            <a class="fa fa-youtube text-danger  btn btn-toolbar  fa-2x p-4 mb-3" target="_blank"
               href="https://github.com/"></a>
        </div>

        <div class="col-lg-6  col-12">
            @using (Html.BeginForm("Contact", "Home", FormMethod.Post, new { @class = "form-horizontal text-center", direction = "rtl", role = "form" }))

            {
                <div class="form-group ">
            <span> الاسم بالكامل</span>
            <input placeholder="الاسم بالكامل" name="username" type="text" class="form-control" />
        </div>
            <div class="form-group ">
                <span> البريد الالكتروني</span>
                <input placeholder="البريد الالكتروني" name="emailaddress" type="text" class="form-control" />
            </div>
            <div class="form-group ">
                <span> موضوع الرسالة</span>
                <input placeholder="موضوع الرسالة" name="subject" type="text" class="form-control" />
            </div>
            <div class="form-group ">
                <span> رسالتك</span>
                <textarea placeholder="مضمون الرسالة" name="body" type="text" class="form-control" rows="8" style="resize: none;"></textarea>
            </div>
            <button type="submit" class="btn btn-primary"> ارسال الرسالة</button>
            }
        </div>
    </div>
</div>

Bsa2er MVC/Bsa2er MVC/Views/Home/Gallery.cshtml
@model IEnumerable<Bsa2er_MVC.Models.Gallery>
@{
    ViewBag.Title = "الصور";
}
<div class="gallery-box">
    <h1 class="h1 text-center m-4">البوم الصور</h1>
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-6 col-lg-4 col-xl-3 p-2">
                <div class="img-d">
                    <img src="~/images/Gallery/@item.Gallery_path" width="150" height="150">
                </div>
            </div>
        }

    </div>
    @*<div class="addImg p-3">
        <label for="imgAdd" class="">إضافة صورة جديدة</label>
        <input type="file" id="imgAdd">
        <input type="button" value="رفع الصورة" class="btn btn-info">
    </div>*@
</div>

Bsa2er MVC/Bsa2er MVC/Views/Home/Index.cshtml
@model IEnumerable<Bsa2er_MVC.Models.CarouselImage>
@{
    ViewBag.Title = "الرئيسة";
}
@if (User.IsInRole("Admin") || User.IsInRole("Owner"))
{
    <div style="text-align:center" class="mb-0 mt-1">
        @Html.ActionLink("اضافة صورة جديدة", "Create", "CarouselImage", null, new { @class = "btn btn-primary", style = "direction:rtl" })
    </div>
}

<a  ></a>
<div class="container-fluid mt-5" style="overflow: hidden;" >
    <div class="row carousel slide " id="myCarousel" data-ride="carousel" data-interval="2000">
        <ul class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ul>

        <div class="carousel-inner">

            @foreach (var item in Model.Select((x, i) => new { Value = x, Index = i }))
            {
                if (item.Index == 0)
                {
                    <div class="carousel-item active">
                        <img src="~/images/CarouselImages/@item.Value.ImagePath" />
                        @if (User.IsInRole("Admin") || User.IsInRole("Owner"))
                        {
                            <div class="carousel-caption text-center" style="top:-10px;">
                                @Html.ActionLink("تعديل", "Edit", "CarouselImage", new { id = item.Value.Id }, new { @class = "btn  btn-warning" }) |
                                @Html.ActionLink("حذف", "Delete", "CarouselImage", new { id = item.Value.Id }, new { @class = "btn  btn-danger" })
                            </div>
                        }

                    </div>
                }
                else
                {
                    <div class="carousel-item ">
                        <img src="~/images/CarouselImages/@item.Value.ImagePath" />
                        @if (User.IsInRole("Admin") || User.IsInRole("Owner"))
                        {
                            <div class="carousel-caption text-center" style="top:-10px;">
                                @Html.ActionLink("تعديل", "Edit", "CarouselImage", new { id = item.Value.Id }, new { @class = "btn  btn-warning" }) |
                                @Html.ActionLink("حذف", "Delete", "CarouselImage", new { id = item.Value.Id }, new { @class = "btn  btn-danger" })
                            </div>
                        }

                    </div>
                }

            }

        </div>

        <a class="carousel-control-prev" data-target="#myCarousel" data-slide="prev"><span class="carousel-control-prev-icon"></span></a>
        <a class="carousel-control-next" data-target="#myCarousel" data-slide="next"><span class="carousel-control-next-icon"></span></a>
    </div>

    <div class="row box col-12 justify-content-around" style="margin-top: 12px;margin-left: 5px; width: 100%;">
        @if (User.IsInRole("Student"))
        {
            <div><a href="/Account/StudentDashboard">التعليم الالكتروني</a></div>
        }
        else if  (User.IsInRole("Owner") | User.IsInRole("Admin")| User.IsInRole("Insructor"))
        {
            <div></div>
        }
        else
        {
            <div><span>@Html.ActionLink("سجل الأن", "Register", "Account", null, null) </span></div>


            <div><span>@Html.ActionLink("تسجيل الدخول", "Login", "Account", null, null)  </span></div>


            <div><span>@Html.ActionLink("التعليم الالكترونى", "", "", null, null)</span></div>
        }
    </div>
</div>

Bsa2er MVC/Bsa2er MVC/Views/Home/News.cshtml
@model IEnumerable<Bsa2er_MVC.Models.news>
@{
    ViewBag.Title = "الأخبار";
}

<div class="tracks-box">
    @*@if (User.IsInRole("Admin"))
    {
        <p>
            @Html.ActionLink("أنشاء خبر جديد", "Create", null, new { dir = "rtl", @class = "btn btn-secondary float-right" })
        </p>
    }*@
    <h1 class="text-center m-4">الاخبار</h1>

    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-6 col-lg-4 col-xl-3 p-2">
                <div class="card bg-info text-light">
                    <div class="img-c">
                        <img width="150" height="150" src="~/images/News/@item.ImagePath">
                    </div>
                    <div class="card-title"> <h5>@item.title</h5></div>
                    <div class="card-body">

                        <p class="card-text"> @item.body.Substring(0, item.body.Length/2) .....</p>
                        @Ajax.ActionLink("قراءة المزيد", "NewsDetails", "News", new { id = item.id }, new AjaxOptions()
                                 {
                                    InsertionMode = InsertionMode.Replace,
                                    UpdateTargetId = "modalBody"
                        }, new { @class = "btn btn-primary", data_toggle = "modal", data_target = "#dnews" })
                        @*@{
                            if (User.IsInRole("Admin"))
                            {

                                @Html.ActionLink("تعديل", "Edit", new { id = item.id }, new { @class = "btn btn-primary" }); <span>|</span>
                                @Html.ActionLink("التفاصيل", "Details", new { id = item.id }, new { @class = "btn btn-primary" }); <span>|</span>
                                @Html.ActionLink("حذف", "Delete", new { id = item.id }, new { @class = "btn btn-primary" });


                            }
                            else
                            {
                                @Ajax.ActionLink("قراءة المزيد", "NewsDetails", "News", new { id = item.id }, new AjaxOptions()
                                {
                                   InsertionMode = InsertionMode.Replace,
                                   UpdateTargetId = "modalBody"
                                }, new { @class = "btn btn-primary", data_toggle = "modal", data_target = "#dnews" })
                            }

                        }*@

                    </div>
                </div>
             </div>
        }

        @* <div class="col-md-6 col-lg-4 col-xl-3 p-2">
                <div class="card bg-info text-light">
                    <div class="img-c">
                        <img src="https://via.placeholder.com/150">
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">عنوان الخبر</h5>
                        <p class="card-text">تفاصيل الخبر</p>
                        <a class="btn btn-primary" data-toggle="modal" data-target="#dnews">قراءة المزيد</a>
                    </div>
                </div>
            </div>*@
    </div>
</div>
<div class="modal fade" id="dnews" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content" id="modalBody">
            <div class="modal-header">
                <h5 class="modal-title text-center col-12 " id="exampleModalLabel" style="text-align: center;"></h5>
            </div>
            <div class="modal-body">
                <img src="~/images/DashBoard/Loading.gif"  width="100" height="100"/>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">إغلاق</button>
            </div>
        </div>
    </div>
</div>

Bsa2er MVC/Bsa2er MVC/Views/Home/Program.cshtml
@model Bsa2er_MVC.Models.Program
@{
    ViewBag.Title = Model.Program_Title;
}
<div class="container">
    <div class="row">
        <div class="col-xs-12 text-center">
            <h1 style="display:block;" class="pb-4 mt-3">@Model.Program_Title</h1>
            <iframe id="prgframe" src="@Model.Program_VideoLink" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            <div class="mb-5">
                <a href="@Model.Program_VideoLink" class="btn btn-info w-50 mt-4 mx-auto " target="_blank">الذهاب الي الدورة</a>
            </div>
            <table class="table  table-bordered table-hover mt-5 mb-5 tab ">
                <tbody>
                    <tr class="d-flex">
                        <td class="col-4">اسم المعلم</td>
                        <td class="col-8">@Model.Instructor.ApplicationUser.fullname</td>
                    </tr>
                    <tr class="d-flex">
                        <td class="col-4">مدة الدورة او البرنامج</td>
                        <td class="col-8">@Model.Program_Duration</td>
                    </tr>
                    <tr class="d-flex">
                        <td class="col-4"> الفئة المستهدفة</td>
                        <td class="col-8">@Model.Program_TargetGroup</td>

                    </tr>

                    <tr class="d-flex">
                        <td class="col-4">طريقة الدراسة</td>
                        <td class="col-8">اون لاين</td>
                    </tr>
                    <tr class="d-flex">
                        <td class="col-4">أهداف الدورة او البرنامج</td>
                        <td class="col-8">
                            @Model.Program_Goals
                        </td>
                    </tr>
                    <tr class="d-flex">
                        <td class="col-4">مميزات الدورة او البرنامج</td>
                        <td class="col-8">
                            @Model.Program_Advantages
                        </td>
                    </tr>
                </tbody>
            </table>
            <p style="margin-top:10px;" class=" mr-5 text-right">ملاحظة : يمكنك التسجيل بالاكاديمية والالتحاق بالبرامج والدورات العلمية والحصول علي شهادات حضور واجتياز</p>
        </div>
    </div>
</div>