Bsa2er MVC/Bsa2er MVC/Models/Program.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Bsa2er_MVC.Models
{
    public class Program
    {
        [Key]
        [Column(Order =0)]
        public int ProgramId { get; set; }
        [Display(Name = "الصورة الرئيسة")]
        public string Program_MainImage { get; set; }
        [Display(Name = "عنوان البرنامج")]
        public string Program_Title { get; set; }
        [Display(Name = "مدة البرنامج")]
        public string Program_Duration { get; set; }
        [Display(Name = "مميزات البرنامج")]
        public string Program_Advantages { get; set; }
        [Display(Name = "اهداف البرنامج")]
        public string Program_Goals { get; set; }
        [Display(Name = "صورة البرنامج")]
        public string Program_ImagePath { get; set; }
        [Display(Name = "نبذة عن البرنامج")]
        public string Program_Body { set; get; }
        [Display(Name = "لينك الفيديو ")]
        public string Program_VideoLink { get; set; }
        [Display(Name = "الفئة المستهدفة")]
        public string Program_TargetGroup { get; set; }
        [Display(Name = "نوع البرنامج")]
        public ProgramType Program_Type { get; set; }
        [Display(Name = "عدد المحاضرات")]

        public int NumOfLecture { get; set; }

        [ForeignKey("Instructor")]
        public string Ins_Id { get; set; }
        public virtual ICollection<Lecture> lectures { get; set; }

        public virtual ICollection<Exam> Exam { get; set; }
        public virtual Instructor Instructor { get; set; }
        public virtual ICollection<StudentsPrograms> StudentsProgram { get; set; }
    }
    public enum ProgramType
    {
        Program,Track, PublicProgram
    }
}

Bsa2er MVC/Bsa2er MVC/Controllers/ProgramsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bsa2er_MVC.Models;

namespace Bsa2er_MVC.Controllers
{
    [Authorize(Roles = "Instructor,Admin,Owner")]
    public class ProgramsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Programs
        public async Task<ActionResult> Index()
        {
            var programs = db.Programs.Include(p => p.Instructor);
            return View(await programs.ToListAsync());
        }
        // GET: Programs/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Program program = await db.Programs.FindAsync(id);
            if (program == null)
            {
                return HttpNotFound();
            }
            return View(program);
        }

        // GET: Programs/Create
        public ActionResult Create(string InstructorId)
        {
            ViewBag.ID = InstructorId;
            return View();
        }

        // POST: Programs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(string InstructorId ,[Bind(Include = "Program_Title,lectures,Program_MainImage,Program_Duration,Program_Body,Program_Advantages,Program_Goals,Program_ImagePath,Program_VideoLink,Program_TargetGroup,Program_Type,NumOfLecture,Ins_Id")] Program program,HttpPostedFileBase imageFile, HttpPostedFileBase mainimageFile)
        {
            if (ModelState.IsValid)
            {
                if (imageFile != null)
                {
                    string[] arr = imageFile.FileName.Split('.');
                    string filename = Guid.NewGuid().ToString() + "." + arr[arr.Length - 1];
                    imageFile.SaveAs(Server.MapPath("~/images/Programs/") + filename);
                    program.Program_ImagePath = filename;
                }
                if (mainimageFile != null)
                {
                    string[] arr2 = mainimageFile.FileName.Split('.');
                    string filename2 = Guid.NewGuid().ToString() + "." + arr2[arr2.Length - 1];
                    mainimageFile.SaveAs(Server.MapPath("~/images/Programs/") + filename2);
                    program.Program_MainImage = filename2;
                }
                program.NumOfLecture = program.lectures.Count();
                program.Ins_Id = InstructorId;
                db.Programs.Add(program);
                await db.SaveChangesAsync();
                if (program.Program_Type==ProgramType.PublicProgram)
                {
                    return RedirectToAction("Index", "InstructorDashboard", new { id = InstructorId });

                }
                else
                {
                    return RedirectToAction("Create", "Exams", new { id = program.ProgramId });

                }


            }
            return View(program);
        }

        // GET: Programs/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Program program = await db.Programs.FindAsync(id);
            if (program == null)
            {
                return HttpNotFound();
            }
            return View(program);
        }

        // POST: Programs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(string InstructorId,[Bind(Include = "ProgramId,lectures,Program_Title,Program_MainImage,Program_Body,Program_Duration,Program_Advantages,Program_Goals,Program_ImagePath,Program_VideoLink,Program_TargetGroup,Program_Type,Ins_Id")] Program program, HttpPostedFileBase imgFile, HttpPostedFileBase mainimgFile)
        {
            if (ModelState.IsValid)
            { 
                if (imgFile != null)
                {
                    string[] arr = imgFile.FileName.Split('.');
                    string imageName = Guid.NewGuid().ToString() + "." + arr[arr.Length - 1];

                    if (program.Program_ImagePath != null)
                    {
                        System.IO.File.Delete(Server.MapPath("~/images/Programs/") + program.Program_ImagePath);
                    }
                    imgFile.SaveAs(Server.MapPath("~/images/Programs/") + imageName);
                    program.Program_ImagePath = imageName;
                }
                if (mainimgFile != null)
                {
                    string[] arr2 = mainimgFile.FileName.Split('.');
                    string imageName2 = Guid.NewGuid().ToString() + "." + arr2[arr2.Length - 1];

                    if (program.Program_MainImage != null)
                    {
                        System.IO.File.Delete(Server.MapPath("~/images/Programs/") + program.Program_MainImage);
                    }
                    mainimgFile.SaveAs(Server.MapPath("~/images/Programs/") + imageName2);
                    program.Program_MainImage = imageName2;
                }
                program.NumOfLecture = program.lectures.Count();
                db.Entry(program).State = EntityState.Modified;

                await db.SaveChangesAsync();
                if (program.Program_Type == ProgramType.PublicProgram)
                {
                    return RedirectToAction("Index", "InstructorDashboard", new { id = InstructorId });

                }
                else
                {
                    return RedirectToAction("Edit", "Exams", new { id = program.ProgramId });

                }
            }
            //ViewBag.Ins_Id = new SelectList(db.Instructors, "InsId", "Degree", program.Ins_Id);
            return View(program);
        }

        // GET: Programs/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Program program = await db.Programs.FindAsync(id);
            if (program == null)
            {
                return HttpNotFound();
            }
            return View(program);
        }

        // POST: Programs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Program program = await db.Programs.FindAsync(id);
            db.Programs.Remove(program);
            await db.SaveChangesAsync();
            return RedirectToAction("Index", "InstructorDashboard");

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Bsa2er MVC/Bsa2er MVC/Views/Programs/Create.cshtml
@model Bsa2er_MVC.Models.Program

@{
    Layout = "~/Views/Shared/Manage.cshtml";
    ViewBag.Title = "اضافة دورة";
}

<h2 style="text-align:center" class="mt-3"> اضافة دورة او برنامج جديد</h2>
@using (Html.BeginForm("Create", "Programs",new { InstructorId = ViewBag.ID}, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
@Html.AntiForgeryToken()
<div class="form-horizontal overflow-hidden text-right w-75 mx-auto">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @*<div class="form-group my-3">
        @Html.LabelFor(model => model.Instructor.ApplicationUser.UserName, htmlAttributes: new { @class = "control-label col-md-2 lead" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Instructor.ApplicationUser.UserName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Instructor.ApplicationUser.UserName, "", new { @class = "text-danger" })
        </div>
    </div>*@
        
    <div class="form-group">
        @Html.LabelFor(model => model.Program_Title, htmlAttributes: new { @class = "control-label col-md-2 mt-3 " })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Program_Title, new { htmlAttributes = new { @class = "form-control mt-3 w-75 mx-auto" } })
            @Html.ValidationMessageFor(model => model.Program_Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Program_MainImage, htmlAttributes: new { @class = "control-label col-md-2 mt-3 " })
        <div class="col-md-10">
            <input type="file" class="form-control mt-3 w-75 mx-auto" name="mainimageFile" id="mainimageFile" />
            @Html.ValidationMessageFor(model => model.Program_MainImage, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Program_Body, htmlAttributes: new { @class = "control-label col-md-2 mt-3" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Program_Body, new { htmlAttributes = new { @class = "form-control mt-3 w-75 mx-auto" } })
            @Html.ValidationMessageFor(model => model.Program_Body, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Program_Duration, htmlAttributes: new { @class = "control-label col-md-2 mt-3 " })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Program_Duration, new { htmlAttributes = new { @class = "form-control mt-3 w-75 mx-auto" } })
            @Html.ValidationMessageFor(model => model.Program_Duration, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Program_Advantages, htmlAttributes: new { @class = "control-label col-md-2 mt-3 " })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Program_Advantages, new { htmlAttributes = new { @class = "form-control mt-3 w-75 mx-auto" } })
            @Html.ValidationMessageFor(model => model.Program_Advantages, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Program_Goals, htmlAttributes: new { @class = "control-label col-md-2 mt-3 " })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Program_Goals, new { htmlAttributes = new { @class = "form-control mt-3 w-75 mx-auto" } })
            @Html.ValidationMessageFor(model => model.Program_Goals, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group enumtype">
        @Html.LabelFor(model => model.Program_Type, htmlAttributes: new { @class = "control-label col-md-2 mt-3 " })
        <div class="col-md-10">
            <select class="form-control mt-3 w-75 mx-auto" onchange="ShowPorgType(event)" name="Program_Type" >
                <option value="@Bsa2er_MVC.Models.ProgramType.Program">برنامج علمي</option>
                <option value="@Bsa2er_MVC.Models.ProgramType.Track">دورة تدريبية</option>
                <option value="@Bsa2er_MVC.Models.ProgramType.PublicProgram">برنامج عام</option>
            </select>
            @Html.ValidationMessageFor(model => model.Program_Type, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group  progimg">
        <label class="control-label col-md-2 mt-3" id="img">صورة البرنامج</label>
        <div class="col-md-10">
            <input type="file" class="form-control mt-3 w-75 mx-auto" name="imageFile" id="imageFile" />
            @*@Html.LabelFor(model => model.Program_ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Program_ImagePath, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Program_ImagePath, "", new { @class = "text-danger" })*@
        </div>
    </div>

    <div class="form-group proglink">
        @Html.LabelFor(model => model.Program_VideoLink, htmlAttributes: new { @class = "control-label col-md-2 mt-3 " })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Program_VideoLink, new { htmlAttributes = new { @class = "form-control mt-3 w-75 mx-auto" } })
            @Html.ValidationMessageFor(model => model.Program_VideoLink, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Program_TargetGroup, htmlAttributes: new { @class = "control-label col-md-2 mt-3" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Program_TargetGroup, new { htmlAttributes = new { @class = "form-control mt-3 w-75 mx-auto" } })
            @Html.ValidationMessageFor(model => model.Program_TargetGroup, "", new { @class = "text-danger" })
        </div>
    </div>



    @*<div class="form-group">
            @Html.LabelFor(model => model.Ins_Id, "Ins_Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Ins_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Ins_Id, "", new { @class = "text-danger" })
            </div>
        </div>*@
</div>
@* المحاضرات*@
<div class="container lectures ">
    <div class="form-group my-3 overflow-hidden w-75 mx-auto text-right">
        <h3>المحاضرات</h3>
        <div class="lecture p-4 text-right" style="border:3px solid #ffd800; border-radius:10%;">
            <label>لينك فيديو المحاضرة </label>
            <div class="mb-3">
                <input class="form-control text-box single-line" type="text" name="lectures[0].Lecture_VideoLink" />
            </div>
            <label>لينك الصوت الخاص بالمحاضرة</label>
            <div class="mb-3">
                <input class="form-control text-box single-line" type="text" name="lectures[0].Lecture_SoundLink" />
            </div>
        </div>
    </div>
    <input type="button" class="btn btn-success mx-5 my-2" id="addlecture" value="إضافة محاضرة" />
</div>

@*  انتهاء المحاضرات *@

@* اضافة امتحان*@

@* اضافة امتحان*@


<div class="form-group mt-5">
    <div>
        @*<a href="" class="btn btn-info btn-block w-25 m-auto text-white createprog">إنشاء الدورة</a>*@

        <input type="submit" value="انشاء الدورة" class="btn btn-info btn-block w-25 m-auto text-white createprog" />

    </div>
</div>
}
@section scripts
{
    <script>
        $(".proglink").hide();
        function ShowPorgType(e) {
            console.log(e.target.value);
            if (e.target.value == "PublicProgram") {
                $(".proglink").show();
                $(".progimg").hide();
                $(".lectures").hide();
            }
            else if (e.target.value == "Program" || e.target.value == "Track") {
                $(".proglink").hide();
                $(".progimg").show();
                $(".lectures").show();
            }
        }


        var currentL = 0;
        $("#addlecture").click(function () {
            currentL++;
            $(".lectures").append(`
                            <div class="form-group my-3 overflow-hidden w-75 mx-auto text-right">
                                <h3>المحاضرات</h3>
                                <div class="lecture p-4 text-right" style="border:3px solid #ffd800; border-radius:10%;">
                                    <label>لينك فيديو المحاضرة </label>
                                    <div class="mb-3">
                                        <input class="form-control text-box single-line" type="text" name="lectures[${currentL}].Lecture_VideoLink" />
                                    </div>
                                    <label>لينك الصوت الخاص بالمحاضرة</label>
                                    <div class="mb-3">
                                        <input class="form-control text-box single-line" type="text" name="lectures[${currentL}].Lecture_SoundLink" />
                                    </div>
                                                                    <input type="button" class="btn btn-danger removelecture" value="إزالة المحاضرة" />
                                </div>
                                </div>
                                         `)
        })
        $(".lectures").on("click", ".removelecture", function () {
            $(this).parent().parent().remove();
        })
        $(".numoflectures").value = currentL;


    </script>
}

Bsa2er MVC/Bsa2er MVC/Views/Programs/Edit.cshtml
@model Bsa2er_MVC.Models.Program

@{
    Layout = "~/Views/Shared/Manage.cshtml";
    ViewBag.Title = "تعديل";
}
<h2 style="text-align:center" class="mt-4">تعديل البرنامج</h2>

@using (Html.BeginForm("Edit", "Programs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal  overflow-hidden text-right w-75 mx-auto">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ProgramId)
    @Html.HiddenFor(model => model.Ins_Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Program_Title, htmlAttributes: new { @class = "control-label col-md-2 mt-3" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Program_Title, new { htmlAttributes = new { @class = "form-control mt-3 w-75 mx-auto" } })
            @Html.ValidationMessageFor(model => model.Program_Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group mt-3" style="min-height:170px;">
        <label id="img" class="control-label col-md-2">الصورة الرئيسية</label>
        <div class="col-md-10">
            <img height="150" width="150" id="img" src="~/images/Programs/@Model.Program_MainImage" dir="rtl" class="float-right" />
            @Html.HiddenFor(model => model.Program_MainImage)
        </div>
    </div>
    <div class="form-group mt-3" style="min-height:50px;">
        <label id="newImg" class="control-label col-md-2">الصورة الجديدة</label>
        <div class="col-md-10">
            <input name="mainimgFile" type="file" id="newImg" class="form-control" />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Program_Body, htmlAttributes: new { @class = "control-label col-md-2 mt-3" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Program_Body, new { htmlAttributes = new { @class = "form-control mt-3 w-75 mx-auto" } })
            @Html.ValidationMessageFor(model => model.Program_Body, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Program_Duration, htmlAttributes: new { @class = "control-label col-md-2 mt-3" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Program_Duration, new { htmlAttributes = new { @class = "form-control mt-3 w-75 mx-auto" } })
            @Html.ValidationMessageFor(model => model.Program_Duration, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Program_Advantages, htmlAttributes: new { @class = "control-label col-md-2 mt-3" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Program_Advantages, new { htmlAttributes = new { @class = "form-control mt-3 w-75 mx-auto" } })
            @Html.ValidationMessageFor(model => model.Program_Advantages, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Program_Goals, htmlAttributes: new { @class = "control-label col-md-2 mt-3" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Program_Goals, new { htmlAttributes = new { @class = "form-control mt-3 w-75 mx-auto" } })
            @Html.ValidationMessageFor(model => model.Program_Goals, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group enumtype">
        @Html.LabelFor(model => model.Program_Type, htmlAttributes: new { @class = "control-label col-md-2 mt-3 " })
        <div class="col-md-10">
            <select class="form-control mt-3 w-75 mx-auto" onchange="ShowPorgType(event)" name="Program_Type">
                @if (Model.Program_Type == Bsa2er_MVC.Models.ProgramType.Program)
                {
                    <option value="@Bsa2er_MVC.Models.ProgramType.Program" selected>برنامج علمي</option>
                    <option value="@Bsa2er_MVC.Models.ProgramType.Track">دورة تدريبية</option>
                    <option value="@Bsa2er_MVC.Models.ProgramType.PublicProgram">برنامج عام</option>
                }
                @if (Model.Program_Type == Bsa2er_MVC.Models.ProgramType.Track)
                {
                    <option value="@Bsa2er_MVC.Models.ProgramType.Program" >برنامج علمي</option>
                    <option value="@Bsa2er_MVC.Models.ProgramType.Track" selected>دورة تدريبية</option>
                    <option value="@Bsa2er_MVC.Models.ProgramType.PublicProgram">برنامج عام</option>
                }
                @if (Model.Program_Type == Bsa2er_MVC.Models.ProgramType.PublicProgram)
                {
                    <option value="@Bsa2er_MVC.Models.ProgramType.Program" >برنامج علمي</option>
                    <option value="@Bsa2er_MVC.Models.ProgramType.Track">دورة تدريبية</option>
                    <option value="@Bsa2er_MVC.Models.ProgramType.PublicProgram" selected>برنامج عام</option>
                }

            </select>
            @Html.ValidationMessageFor(model => model.Program_Type, "", new { @class = "text-danger" })
        </div>
    </div>
    @if (!(Model.Program_Type == Bsa2er_MVC.Models.ProgramType.PublicProgram))
    {
        <div class="form-group mt-3 progimg" style="min-height:170px;">
            <label id="img" class="control-label col-md-2">صورة البرنامج / الدورة</label>
            <div class="col-md-10">
                <img height="150" width="150" id="img" src="~/images/Programs/@Model.Program_ImagePath" dir="rtl" class="float-right" />
                @Html.HiddenFor(model => model.Program_ImagePath)
            </div>
        </div>
        <div class="form-group mt-3 progimg" style="min-height:50px;">
            <label id="newImg" class="control-label col-md-2">الصورة الجديدة</label>
            <div class="col-md-10">
                <input name="imgFile" type="file" id="newImg" class="form-control" />
            </div>
        </div>
    }
    @if (Model.Program_Type == Bsa2er_MVC.Models.ProgramType.PublicProgram)
    {
        <div class="form-group proglink">
            @Html.LabelFor(model => model.Program_VideoLink, htmlAttributes: new { @class = "control-label col-md-2 mt-3 " })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Program_VideoLink, new { htmlAttributes = new { @class = "form-control mt-3 w-75 mx-auto" } })
                @Html.ValidationMessageFor(model => model.Program_VideoLink, "", new { @class = "text-danger" })
            </div>
        </div>

    }
    <div class="form-group">
        @Html.LabelFor(model => model.Program_TargetGroup, htmlAttributes: new { @class = "control-label col-md-2 mt-3" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Program_TargetGroup, new { htmlAttributes = new { @class = "form-control mt-3 w-75 mx-auto" } })
            @Html.ValidationMessageFor(model => model.Program_TargetGroup, "", new { @class = "text-danger" })
        </div>
    </div>

    @if (!(Model.Program_Type == Bsa2er_MVC.Models.ProgramType.PublicProgram))
    {
        <div class="container lectures ">
            <div class="form-group my-3 overflow-hidden w-75 mt-5 mx-auto text-right">
                <h3>المحاضرات</h3>
                @foreach (var item in Model.lectures.Select((x,i)=> new { Value=x,Index=i }))
                {
            <div class="lecture p-4 text-right" style="border:3px solid #ffd800; border-radius:10%;">
                <input type="hidden" value="@item.Value.Lecture_Id" name="lectures[@item.Index].Lecture_Id" />
                <input type="hidden" value="@item.Value.Program_Id" name="lectures[@item.Index].Program_Id" />
                <label>لينك فيديو المحاضرة </label>
                <div class="mb-3">
                    <input class="form-control text-box single-line" type="text" value="@item.Value.Lecture_VideoLink" name="lectures[@item.Index].Lecture_VideoLink" />
                </div>
                <label>لينك الصوت الخاص بالمحاضرة</label>
                <div class="mb-3">
                    <input class="form-control text-box single-line" type="text" value="@item.Value.Lecture_SoundLink" name="lectures[@item.Index].Lecture_SoundLink" />
                </div>
            </div>
                }
            </div>
        </div>
    }
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="تعديل" class="btn btn-info btn-block w-25 m-auto text-white" />
        </div>
    </div>
</div>
}
@section scripts 
    {
    <script>

         
        if ($(".progtype").val() == "2") {
                $(".proglink").show();
                $(".progimg").hide();
                $(".lectures").hide();
            }
        else if ($(".progtype").val() == "0" || ($(".progtype").val() == "1" )) {
                $(".proglink").hide();
                $(".progimg").show();
            }

        $("#addlecture").click(function () {
            currentL++;
            $(".lectures").append(`
                        <div class="form-group my-3 overflow-hidden w-75 mx-auto text-right">
                     <input type="number" value="@Model.ProgramId" hidden name="lectures[${currentL}].Lecture_Id" />
                            <h3>المحاضرات</h3>
                            <div class="lecture p-4 text-right" style="border:3px solid #ffd800; border-radius:10%;">
                                <label>لينك فيديو المحاضرة </label>
                                <div class="mb-3">
                                    <input class="form-control text-box single-line" type="text" name="lectures[${currentL}].Lecture_VideoLink" />
                                </div>
                                <label>لينك الصوت الخاص بالمحاضرة</label>
                                <div class="mb-3">
                                    <input class="form-control text-box single-line" type="text" name="lectures[${currentL}].Lecture_SoundLink" />
                                </div>
                                                                <input type="button" class="btn btn-danger removelecture" value="إزالة السؤال" />
                            </div>
                            </div>
                                     `)
        })
        $(".lectures").on("click", ".removelecture", function () {
            $(this).parent().parent().remove();
        })
        $(".numoflectures").value = currentL;
    </script>
    }