Bsa2er MVC/Bsa2er MVC/Models/Gallery.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Bsa2er_MVC.Models
{
    public class Gallery
    {
        [Key]
        public int G_Id { get; set; }
        public string Gallery_path { get; set; }
    }
}

Bsa2er MVC/Bsa2er MVC/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bsa2er_MVC.Models;

namespace Bsa2er_MVC.Controllers
{
    public class GalleryController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Gallery
       /* public async Task<ActionResult> Index()
        {
            return View(await db.Galleries.ToListAsync());
        }*/

        // GET: Gallery/Details/5
        /*public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gallery gallery = await db.Galleries.FindAsync(id);
            if (gallery == null)
            {
                return HttpNotFound();
            }
            return View(gallery);
        }*/

        // GET: Gallery/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Gallery/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Gallery_path")] Gallery gallery,HttpPostedFileBase img)
        {
            if (ModelState.IsValid)
            {
                gallery.Gallery_path = Server.MapPath("~/images/Gallery/default.jpg");
                if (img != null)
                {
                    string[] arr = img.FileName.Split('.');
                    string imageName = Guid.NewGuid().ToString() + "." + arr[arr.Length - 1];
                    img.SaveAs(Server.MapPath("~/images/Gallery/") + imageName);
                    gallery.Gallery_path = imageName;
                }
                
                db.Galleries.Add(gallery);
                await db.SaveChangesAsync();
                return RedirectToAction("DashBoardPage","DashBoard");
            }

            return View(gallery);
        }

        // GET: Gallery/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gallery gallery = await db.Galleries.FindAsync(id);
            if (gallery == null)
            {
                return HttpNotFound();
            }
            return View(gallery);
        }

        // POST: Gallery/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "G_Id,Gallery_path")] Gallery gallery,HttpPostedFileBase img)
        {
            if (ModelState.IsValid)
            {
                if (img != null)
                {
                    string[] arr = img.FileName.Split('.');
                    string imageName = Guid.NewGuid().ToString() + "." + arr[arr.Length - 1];

                    if (gallery.Gallery_path != null)
                    {
                        System.IO.File.Delete(Server.MapPath("~/images/News/") + gallery.Gallery_path);
                    }
                    img.SaveAs(Server.MapPath("~/images/News/") + imageName);
                    gallery.Gallery_path = imageName;
                }
                db.Entry(gallery).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("DashBoardPage", "DashBoard");
            }
            return View(gallery);
        }

        // GET: Gallery/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gallery gallery = await db.Galleries.FindAsync(id);
            if (gallery == null)
            {
                return HttpNotFound();
            }
            return View(gallery);
        }

        // POST: Gallery/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Gallery gallery = await db.Galleries.FindAsync(id);
            db.Galleries.Remove(gallery);
            await db.SaveChangesAsync();
            return RedirectToAction("DashBoardPage", "DashBoard");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Bsa2er MVC/Bsa2er MVC/Views/Gallery/Create.cshtml
@model Bsa2er_MVC.Models.Gallery

@{
    ViewBag.Title = "أنشاء صورة";
}

<h2 dir="rtl" class="text-center mb-5">انشاء صورة جديدة</h2>

@using (Html.BeginForm("Create","Gallery",FormMethod.Post,new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal text-right mb-2 mt-2" dir="rtl" style="height:50px">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group" style="height:40px;" dir="rtl">
            <label class = "control-label col-md-2">ادخل الصورة</label>
            @*@Html.LabelFor(model => model.Gallery_path, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                <input type="file"  class = "form-control" accept="image" name="img"/>
                @*@Html.EditorFor(model => model.Gallery_path, new { htmlAttributes = new { @class = "form-control" } })*@
                @*@Html.ValidationMessageFor(model => model.Gallery_path, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="انشأ" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("الرجوع الي لوحة التحكم", "DashBoardPage","DashBoard")
</div>

Bsa2er MVC/Bsa2er MVC/Views/Gallery/Delete.cshtml
@model Bsa2er_MVC.Models.Gallery

@{
    ViewBag.Title = "Delete";
}

<h2 class="text-center mb-3" dir="rtl">حذف الصورة</h2>

<h3 class="text-right mr-3" dir="rtl">هل انت متأكد تريد حذف هذه الصورة؟</h3>
<div class=" justify-content-between text-right mr-3" dir="rtl" style="min-height:200px;">
    <dl class="dl-horizontal">
        <dt>
            <lable id="img">الصورة </lable>
        </dt>

        <dd>
            <img height="150" width="150" id="img" src="~/images/Gallery/@Model.Gallery_path" />
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="حذف" class="btn btn-primary" /> 
            @Html.ActionLink("to DashBoard", "DashBoardPage","DashBoard",null, new { @class = "float-left" })
        </div>
    }
</div>

Bsa2er MVC/Bsa2er MVC/Views/Gallery/Details.cshtml
@model Bsa2er_MVC.Models.Gallery

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Gallery</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Gallery_path)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gallery_path)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.G_Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Bsa2er MVC/Bsa2er MVC/Views/Gallery/Edit.cshtml
@model Bsa2er_MVC.Models.Gallery

@{
    ViewBag.Title = "Edit";
}

<h2 class="text-center text-right" dir="rtl">تعديل الصورة</h2>

@using (Html.BeginForm("Edit", "Gallery", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal text-right" dir="rtl" style="height:250px;">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.G_Id)
    <div class="form-group"style="height:100px">
        <label class="control-label col-md-2"> الصورة</label>
        @*@Html.LabelFor(model => model.Gallery_path, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="col-md-10">
            <img width="150" height="150" src="~/images/Gallery/@Model.Gallery_path"/>
            @*@Html.EditorFor(model => model.Gallery_path, new { htmlAttributes = new { @class = "form-control" } })*@
            @*@Html.ValidationMessageFor(model => model.Gallery_path, "", new { @class = "text-danger" })*@
        </div>
    </div>

    <div class="form-group" dir="rtl" style="height:70px">
        <label class="control-label col-md-2">ادخل الصورة الجديدة</label>
        @*@Html.LabelFor(model => model.Gallery_path, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="col-md-10">
            <input type="file" class="form-control" accept="image" name="img" />
            @*@Html.EditorFor(model => model.Gallery_path, new { htmlAttributes = new { @class = "form-control" } })*@
            @*@Html.ValidationMessageFor(model => model.Gallery_path, "", new { @class = "text-danger" })*@
        </div>
    </div>

    <div class="form-group" dir="rtl" >
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="حفظ" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("الرجوع الي لوحة التحكم", "DashBoardPage", "DashBoard")
</div>

Bsa2er MVC/Bsa2er MVC/Views/Gallery/Index.cshtml
@model IEnumerable<Bsa2er_MVC.Models.Gallery>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Gallery_path)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Gallery_path)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.G_Id }) 
            @Html.ActionLink("Details", "Details", new { id=item.G_Id }) 
            @Html.ActionLink("Delete", "Delete", new { id=item.G_Id })
        </td>
    </tr>
}

</table>